dist: jammy
sudo: required
services:
  - docker
 
# Get Google Chrome headless browser for Angular tests
# Install latest Docker CE so we can use Dockerfile outside build context
addons:
  chrome: stable
 
# Install any dependencies, update Docker Compose to 1.23.2 so we can use Dockerfile outside build context
before_install:
 - docker --version
 - docker-compose --version
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
 
#install:
 
# Build development images for test
before_script:
  - docker build ./todo-view -f ./todo-view/Dockerfile.dev -t moccogov/todo-view-test
  - docker build ./todo-cache-service -f Dockerfile.nodejs.dev -t moccogov/todo-cache-service-test
  - export CHROME_BIN='/usr/bin/chromium'
 
# Run some tests
script:
  - docker run moccogov/todo-view-test npm test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - docker run moccogov/todo-cache-service-test npm test
 
after_success:
  # Build Production Images for deployment
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
 
  # Login to Docker Hub
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
 
  # Take the built production images and push to Docker Hub
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml push